#! /bin/bash

HOST="localhost:3000"

printf "all users:\n"
curl -H "Accept: application/json" $HOST/users

printf "\nuser 1\n"
curl -H "Accept: application/json" $HOST/users/1

printf "\n"

# fails because no CSRF header
#curl -X POST \
#  -H "Content-Type: application/json" \
#  -H "Accept: application/json"
#  -d '{"name": "scriptgenerated", "email": "email@example.com"}'\
#  $HOST/users