#! /bin/bash

HOST="localhost:3000"

printf "all users:\n"
curl -H "Accept: application/json" $HOST/users

NEWUSERID=$(curl -s -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{"name": "scriptgenerated", "email": "email@example.com"}' \
  $HOST/users | jq -r '.id')
printf "\n\nCreated user with ID $NEWUSERID:\n"
curl -H "Accept: application/json" $HOST/users/$NEWUSERID

printf "\n\nDeleting user with ID $NEWUSERID..."
curl -X DELETE \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  $HOST/users/$NEWUSERID

printf "\n\nall users:\n"
curl -H "Accept: application/json" $HOST/users

printf "\n"